### PR TITLE
Made mobile navbar transition smoother

### PR DESCRIPTION
**Pull request by IvanMOA**
I made the transition for opening the navbar on mobile smoother, instead of it popping out of nowhere we can now see it expand and contract

### CODE REVIEW

**Comment by IvanMOA** [comment]
Forgot to add it to the commands page, will be adding in later, and also, did you hardcoded some url's to avoid showing the .html at the end of them ?

**Comment by alexcraviotto** [comment]
> I made the transition for opening the navbar on mobile smoother, instead of it popping out of nowhere we can now see it expand and contract

Thanks for the contribution, it looks great on the website :heart:

> Forgot to add it to the commands page, will be adding in later, and also, did you hardcoded some url's to avoid showing the .html at the end of them ?

When you add it to the command page I do the merge!

**Comment by IvanMOA** [comment]
I added it to the commands page, ended up creating two new files to have a single source of truth and avoid having duplicate code

**Comment by alexcraviotto** [comment]
Thank you, I appreciate it very much.

**Comment by alexcraviotto** [comment]
Thank you, I appreciate it very much.

**Pull request merged**
